### ISSUE TITLE
scripts/genomon_pipeline/run.py のmultiprocess = 10　固定

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/GenomonPipeline#101]
10 固定でjobが常時10投入された状態になる

最大値を設けた上で、変更できるようにしてほしい

プロセスは1ジョブに対し
orgqsub　、　/usr/local/package/ruby/2.1.5/bin/ruby 、
/usr/local/package/python2.7/current/bin/python /home/hiroko/.local/bin/genomon_pipeline
の３つのプロセスが走っています

**Comment by roko-t** [comment]
1198検体をmultiprocess = 100で解析。100 x 3 = 300 processes 実行中。問題なし。

**Comment by ken0-1n** [comment]
binのgenomon_pipelineのmultiprocessオプションで変更が可能
