### ISSUE TITLE
Reference FASTAに関して

### ISSUE THREAD

**Issue by eigoshimizu** [Genomon-Project/GenomonPipeline#11]
/home/w3varann/database/hg19
chr1
chr2
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr20
chr21
chr22
chrX
chrY
chrM

chr1_gl000191_random
chr1_gl000192_random
chr4_gl000193_random
chr4_gl000194_random
chr7_gl000195_random
chr8_gl000196_random
chr8_gl000197_random
chr9_gl000198_random
chr9_gl000199_random
chr9_gl000200_random
chr9_gl000201_random
chr11_gl000202_random
chr17_gl000203_random
chr17_gl000204_random
chr17_gl000205_random
chr17_gl000206_random
chr18_gl000207_random
chr19_gl000208_random
chr19_gl000209_random
chr21_gl000210_random
chrUn_gl000211
chrUn_gl000212
chrUn_gl000213
chrUn_gl000214
chrUn_gl000215
chrUn_gl000216
chrUn_gl000217
chrUn_gl000218
chrUn_gl000219
chrUn_gl000220
chrUn_gl000221
chrUn_gl000222
chrUn_gl000223
chrUn_gl000224
chrUn_gl000225
chrUn_gl000226
chrUn_gl000227
chrUn_gl000228
chrUn_gl000229
chrUn_gl000230
chrUn_gl000231
chrUn_gl000232
chrUn_gl000233
chrUn_gl000234
chrUn_gl000235
chrUn_gl000236
chrUn_gl000237
chrUn_gl000238
chrUn_gl000239
chrUn_gl000240
chrUn_gl000241
chrUn_gl000242
chrUn_gl000243
chrUn_gl000244
chrUn_gl000245
chrUn_gl000246
chrUn_gl000247
chrUn_gl000248
chrUn_gl000249

chr4_ctg9_hap1
chr6_apd_hap1
chr6_cox_hap2
chr6_dbb_hap3
chr6_mann_hap4
chr6_mcf_hap5
chr6_qbl_hap6
chr6_ssto_hap7
chr17_ctg5_hap1
ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes

/home/w3varann/database/GRCh37.p5
This is the integrated reference sequence from the GRCh37 primary assembly (chromosomal plus unlocalized and unplaced contifg), the rCRS mitochondrial sequence (AC:NC_012920), Human herpesvirus 4 type (AC:NC_007605) and the concatenated decoy sequences( hs37d5cs.fa.gz)

1) Human Genome
ftp://ftp.ncbi.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh37/special_requests/
GRCh37-lite.fa.gz

2) Human herpesvirus 4 complete wild type genome
http://www.ncbi.nlm.nih.gov/nuccore/82503188?report=fasta

3) decoy
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/
hs37d5cs.fa.gz

4) rCRS (revised Cambridge REference Sequence) of the Human Mitochondrial DNA
http://www.mitomap.org/MITOMAP/HumanMitoSeq
http://www.ncbi.nlm.nih.gov/nuccore/251831106

**Comment by friend1ws** [comment]
OK!!!
