### ISSUE TITLE
multiprocessing数が多い時にqsubで落ちる件

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#117]
以下のシンプルな例が問題の本質を理解するのに役に立つであろう

https://gist.github.com/friend1ws/c7ce088608aabfd9e103

**Comment by ken0-1n** [comment]
qsub -l s_vmemで指定した値より、使用する（プロセスが確保する）VMEMの値が大きいため,qsubが落ちる。

プロセスが確保するVMEMのデフォルト値は一般的に大きいようだ。
sleepでもVMEMを100MB確保している
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
kchiba    4098  0.0  0.0 100904   576 pts/7    S+   12:49   0:00 sleep 20 

基本的には確保だけでswapなどはしていないと推測できるので、
qsub  -l s_vmem=128G,mem_req=64G
ということができるようにすればよいか・・・という方向で解決を目指す

**Comment by ken0-1n** [comment]
orgqsub -l s_vmem=128G,mem_req=64G
という方向で解決をした。
