### ISSUE TITLE
drmaaをqsubより優先にする

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#136]
基本drmaaにして、
--qsub_sync
とかにするとqsubにするようにしていただけますでしょうか？

あと、３回投げ直す機能をqsub_syncにもつけていただけると嬉しいです。

**Comment by ken0-1n** [comment]
基本drmaa
--disable_drmaa
でqsub syncになります。

3回投げ直す機能をqsub_syncにつけるのは別のissueに移動する
