### ISSUE TITLE
version 2.0.2について負荷が高い

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#138]
64GBでqsubしていて、これまでは大丈夫だったが、今回のバージョンでは、coveregeのところでメモリ不足で落ちた。負荷を減らせないか？

**Comment by ken0-1n** [comment]
v2.0.2のメモリ使用量と、スクリプト修正後のメモリ使用量を調査して、こちらのissueにコメントお願いします。

**Comment by ken0-1n** [comment]
改修済み
