### ISSUE TITLE
stage_task.pyについていくつか気がついたことメモ

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#141]
１．現在投げなおしのときに、retval.exitStatusしか見ていないが、retval.hasExitedについては、見なくて良いのか？？自分としては、一応こちらも正常値かどうかをチェックした方が、プログラムの安定性的に良いと思う。

２．run_conの値を参照しているが、これを__init__の引数に渡した方が、モジュールとしてすっきりするのではないか？これをやると、genomon_pipeline.stage_staskで、ほかプログラムから呼び出しが可能になるのでユーティリティーが著しく向上する。stage_task.pyだけを利用しようとして、run_confの値を参照していたために諦めた経緯があり。

３．ほとんどのスクリプトのテンプレートで、logのpathをしていしているが、drmaaの場合はこれを、stage_task.pyの中で直にしていしている。スクリプトのテンプレートの{log}を消すことはできるか？？

**Comment by ken0-1n** [comment]
１について、.こういうパターンがhasexitedでとれるようなので、追加しておく。
==============================================================
owner                kchiba
jobnumber            7293090
taskid               2
slots                1
pe_taskid            NONE
granted_pe           NONE
exit_status          0
failed               26
qname                ljobs.q
hostname             sc437i
jobname              bwa_align_20160105_1841_770558
qsub_time            20160105-18:41:07
start_time           19700101-09:00:00
end_time             19700101-09:00:00
ru_wallclock         0
cpu                  0.0
mem                  0.0
maxvmem              0.0G
r_mem                10.6G
r_q                  ljobs.q,lmem.q
r_cpu                NONE
qdel                 NONE
failed_txt           Opening output file
recommended_queue    NONE
recommended_memory   10.6G
recommended_option   -l s_vmem=10.6G,mem_req=10.6G
