### ISSUE TITLE
mutation, sv, summaryの挙動について

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#142]
３連休でgenomonをかけまくっているのですが、特にmutationでエラーが多発しています。
これは、もう一度やると通る感じなので、スパコンのせいという理由が強いと思うのですが（でも、３回投げなおしているのになぜだろう。。）、中途半端な状態でもう一度genomonを実行したときに、
特にsummaryについては、最終結果が出ているものもまたやり直してしまう。またsvについてはちょっと挙動が謎。

ということで、
１．挙動を確認したい
２．genomonの構成について開発者間でコンセンサスを取りたい（これから機能を追加する時などに、どういった仕様にするか？）

まあ、少しruffusの挙動が謎ですし、あまりactiveに更新している感じもないので、
1年くらいは我慢して使うけど、alternativeを考えていきたいところですね。。。

**Comment by ken0-1n** [comment]
summaryについて対応済み
SVの問題については#178をopenする
