### ISSUE TITLE
インストールしたバージョンを残したい

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#146]
インストールしたGenomonバージョンを残したいという要望があった。

**Comment by ken0-1n** [comment]
対応策を出しておく
①--home="" で好きなインストールに保存、
②genomon_pipleineを起動するshellを用意して、そこで環境変数を変更できるようにする。

他の方法があればコメントよろしくお願いします。

**Comment by friend1ws** [comment]
自分の考える対応策
１．pyenvとかvirturalenvとか使えないですかね？
まあ小川研であれば、ちょっと敷居が高いかな。。。

２．全てのバージョンを保存しておいて共有
多分、自分たちの周りではomegaに全てのバージョンをインストールする感じになるかもしれない。
とすると、omegaにinstallされているgenomonを共有してしまうとかいいかもしれない。
そして、それぞれのバージョンのconfigファイルを固定して、
またそれぞれのバージョンを動かすスクリプトを共有する。

**Comment by ken0-1n** [comment]
２．で対応済み
