### ISSUE TITLE
w3varannに置いてあるsimple repeatについて

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#148]
細かいことなのですが、一応気がついたことなので、お手すきのときに検討していただけると嬉しいです。

１．拡張子が.bed.bgzになっているが意味はあるか？
２．start座標がUCSCからダウンロードしたものから-1引かれているが、そもそもUCSCのbed formatは、もともとが示す位置から-1されているので、引く必要はないと思うがどうか？

**Comment by ken0-1n** [comment]
指摘の通りに改修した
