### ISSUE TITLE
coverage.pyのエラーハンドリング

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#149]
{BEDTOOLS} sort -i {output}.noheader.bed > {output}.sort.bed
上記のbedtoolsの実行で失敗したのだけれど、エラーハンドリングされていないため、処理が続行され、qsub job がexit 0で終了した。

bedtoolsの失敗の原因は、ld_library_pathの設定ミスのため、bedtoolsの失敗で処理が終わることが望ましい。

優先度低

**Comment by aokad** [comment]
対応済み
