### ISSUE TITLE
post_analysisのマージファイルについて

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#162]
変異コールの結果やSV検出の結果が更新された時は、post_analysisのマージファイルも更新した方が良い。

現在の仕様では、post_analysisも他の機能とおなじく、ファイルが存在していたら処理を行わない。

たとえば、変異コールをパラメータを変えてもう一回実行しようと思い、mutationディレクトリだけ削除して、変異コールを再実行しても、post_analysisの結果は更新されない。そのためmutationディレクトリとpost_analysisディレクトリは別の結果が格納されている状態になる。

**Comment by aokad** [comment]
対応済み
