### ISSUE TITLE
annot_utilsの利用に伴う、RNA-seq用のconfig fileの変更点

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#171]
まず、fusionfusion, fusion_utils, intron_retention_utils, GenomonExpression, annot_utilsの最新versionをダウンロード（全部rc, release candidateがついてます）。

[fusionfusion]
annotation_dir = /home/w3varann/genomon_pipeline-2.4.1/tools/fusionfusion-0.2.0beta/resource
-> 削除

params=
-> params= --grc (GRCh38の場合は --genome_id hg38を付与）

filt_params = --filter_same_gene
-> filt_params = --filter_same_gene --grc　(GRCh38の場合は --genome_id hg38を付与）

[genomon_expression]
annotation_file = /home/w3varann/genomon_pipeline-2.4.1/tools/GenomonExpression-0.2.0/resource/exon.GRCh37.bed
-> 削除

params=
-> params= --grc (GRCh38の場合は --genome_id hg38を付与）

[intron_retention]
ref_gene = /home/w3varann/genomon_pipeline-2.4.1/tools/intron_retention_utils-0.2.0beta/resource/refGene.txt.gz
-> 削除

params= --chr_name_list /home/w3varann/genomon_pipeline-2.4.1/tools/intron_retention_utils-0.2.0beta/resource/ucsc2grch.txt
-> params= --grc (GRCh38の場合は --genome_id hg38を付与）

**Comment by ken0-1n** [comment]
4948af675659827fed35fba2a8ffbebfa68662a3
にて対応
