### ISSUE TITLE
bwa_align実行中にUGEがReschedulingになると誤BAMが作成されることがある

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/GenomonPipeline#173]
bwa_align実行中にUGEがReschedulingになると、bam mem完了前にbamsortが開始されてしまうことがあり、正しくないBAMファイルが作成される。（600件中2件で発生）
FASTQファイルとBAMファイルのリード数の照合など、bwa_align　の正常終了確認機能を入れてほしい。

**Comment by ken0-1n** [comment]
`set -o pipefail` を追加し、正常終了確認をできるようにした。
