### ISSUE TITLE
リファレンスゲノムのディレクトリ構成について

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#19]
/home/w3varann/database/hg19 ディレクトリ内にある、bwa indexファイルのバージョンが分からないので以下のようなディレクトリ構成を希望します（検討が必要です）。

$ ls -l /home/w3varann/database/
bwa-0.7.8
bwa-0.7.10
hg19 → bwa-0.7.8

**Comment by eigoshimizu** [comment]
下記のように対応しました。
*.fa のディレクトリの下に、FASTA ファイルを置いておき、そこから soft link で
*.bowtie*, *.bwa*, *.samtools* にリンクを張り、そこに index ファイルを作りました。
genomon.cfg は、アップデートしなければなりません。

GRCh37.p5.bowtie-2.2.5
GRCh37.p5.bwa-0.7.8
GRCh37.p5.fa
GRCh37.p5.samtools-1.2


hg19.bwa-0.7.8
hg19.fa
hg19.samtools-1.2

**Comment by eigoshimizu** [comment]
<GRCh37.pt.fa>
GRCh37-lite-noMT.fa
rCRS.fa
human_hs_4_complete.fa
hs37d5cs.fa

>1 CM000663.1 Homo sapiens chromosome 1, GRCh37 primary reference assembly
>2 CM000664.1 Homo sapiens chromosome 2, GRCh37 primary reference assembly
>3 CM000665.1 Homo sapiens chromosome 3, GRCh37 primary reference assembly
>4 CM000666.1 Homo sapiens chromosome 4, GRCh37 primary reference assembly
>5 CM000667.1 Homo sapiens chromosome 5, GRCh37 primary reference assembly
>6 CM000668.1 Homo sapiens chromosome 6, GRCh37 primary reference assembly
>7 CM000669.1 Homo sapiens chromosome 7, GRCh37 primary reference assembly
>8 CM000670.1 Homo sapiens chromosome 8, GRCh37 primary reference assembly
>9 CM000671.1 Homo sapiens chromosome 9, GRCh37 primary reference assembly
>10 CM000672.1 Homo sapiens chromosome 10, GRCh37 primary reference assembly
>11 CM000673.1 Homo sapiens chromosome 11, GRCh37 primary reference assembly
>12 CM000674.1 Homo sapiens chromosome 12, GRCh37 primary reference assembly
>13 CM000675.1 Homo sapiens chromosome 13, GRCh37 primary reference assembly
>14 CM000676.1 Homo sapiens chromosome 14, GRCh37 primary reference assembly
>15 CM000677.1 Homo sapiens chromosome 15, GRCh37 primary reference assembly
>16 CM000678.1 Homo sapiens chromosome 16, GRCh37 primary reference assembly
>17 CM000679.1 Homo sapiens chromosome 17, GRCh37 primary reference assembly
>18 CM000680.1 Homo sapiens chromosome 18, GRCh37 primary reference assembly
>19 CM000681.1 Homo sapiens chromosome 19, GRCh37 primary reference assembly
>20 CM000682.1 Homo sapiens chromosome 20, GRCh37 primary reference assembly
>21 CM000683.1 Homo sapiens chromosome 21, GRCh37 primary reference assembly
>22 CM000684.1 Homo sapiens chromosome 22, GRCh37 primary reference assembly
>X CM000685.1 Homo sapiens chromosome X, GRCh37 primary reference assembly
>Y CM000686.1 Homo sapiens chromosome Y, GRCh37 primary reference assembly, with PAR regions masked with Ns (bases 10001..2649520 & 59034050..59363566)
>GL000207.1 Homo sapiens chromosome 18 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000226.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000229.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000231.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000210.1 Homo sapiens chromosome 21 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000239.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000235.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000201.1 Homo sapiens chromosome 9 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000247.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000245.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000197.1 Homo sapiens chromosome 8 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000203.1 Homo sapiens chromosome 17 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000246.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000249.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000196.1 Homo sapiens chromosome 8 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000248.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000244.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000238.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000202.1 Homo sapiens chromosome 11 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000234.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000232.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000206.1 Homo sapiens chromosome 17 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000240.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000236.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000241.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000243.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000242.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000230.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000237.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000233.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000204.1 Homo sapiens chromosome 17 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000198.1 Homo sapiens chromosome 9 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000208.1 Homo sapiens chromosome 19 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000191.1 Homo sapiens chromosome 1 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000227.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000228.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000214.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000221.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000209.1 Homo sapiens chromosome 19 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000218.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000220.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000213.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000211.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000199.1 Homo sapiens chromosome 9 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000217.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000216.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000215.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000205.1 Homo sapiens chromosome 17 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000219.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000224.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000223.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000195.1 Homo sapiens chromosome 7 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000212.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000222.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000200.1 Homo sapiens chromosome 9 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000193.1 Homo sapiens chromosome 4 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000194.1 Homo sapiens chromosome 4 unlocalized genomic contig, GRCh37 reference primary assembly
>GL000225.1 Homo sapiens unplaced genomic contig, GRCh37 reference primary assembly
>GL000192.1 Homo sapiens chromosome 1 unlocalized genomic contig, GRCh37 reference primary assembly
>MT NC_012920|Homo sapiens mitochondrion, complete genome.
>NC_007605 Human herpesvirus 4 complete wild type genome.
>hs37d5

**Comment by eigoshimizu** [comment]
<<<Directory の構成>>>
GRCh37.p5
GRCh37.p5.bowtie-2.2.5
GRCh37.p5.bwa-0.7.8
GRCh37.p5.fa
GRCh37.p5.samtools-1.2

<soft link>
GRCh37.p5/gGRCh37.p5.fa -> GRCh37.p5.fa/GRCh37.p5.fa
GRCh37.p5/gGRCh37.p5.fa.amb -> GRCh37.p5.bwa-0.7.8/GRCh37.p5.fa.amb
GRCh37.p5/gGRCh37.p5.fa.ann -> GRCh37.p5.bwa-0.7.8/GRCh37.p5.fa.ann
GRCh37.p5/gGRCh37.p5.fa.bwt -> GRCh37.p5.bwa-0.7.8/GRCh37.p5.fa.bwt
GRCh37.p5/gGRCh37.p5.fa.fai -> GRCh37.p5.samtools-1.2/GRCh37.p5.fa.fai
GRCh37.p5/gGRCh37.p5.fa.pac -> GRCh37.p5.bwa-0.7.8/GRCh37.p5.fa.pac
GRCh37.p5/gGRCh37.p5.fa.sa -> GRCh37.p5.bwa-0.7.8/GRCh37.p5.fa.sa


hg19
hg19.bowtie-2.2.5
hg19.bwa-0.7.8
hg19.fa
hg19.samtools-1.2
<soft link>
hg19.fa/hg19.fa     -> hg19.fa/hg19.fa
hg19.fa/hg19.fa.amb -> hg19.bwa-0.7.8/hg19.fa.amb
hg19.fa/hg19.fa.ann -> hg19.bwa-0.7.8/hg19.fa.ann
hg19.fa/hg19.fa.bwt -> hg19.bwa-0.7.8/hg19.fa.bwt
hg19.fa/hg19.fa.fai -> hg19.samtools-1.2/hg19.fa.fai
hg19.fa/hg19.fa.pac -> hg19.bwa-0.7.8/hg19.fa.pac
hg19.fa/hg19.fa.sa  -> hg19.bwa-0.7.8/hg19.fa.sa

**Comment by friend1ws** [comment]
こののちの「w3varannのデータベース整理」に引き継ぐ
