### ISSUE TITLE
MPI への対応

### ISSUE THREAD

**Issue by eigoshimizu** [Genomon-Project/GenomonPipeline#3]
* RunTask objectでの実装

* HGC MPI でのテスト

**Comment by eigoshimizu** [comment]
Python DRMAA の動作確認。
/home/eigos/Data/DRMAA.

現在は、DRMAA は使用していません。

DRMAA および MPI をサポートするか？

**Comment by eigoshimizu** [comment]
qsub, DRMAA はサポートしています。

MPIに関しては、次のリリースではサポートしません。

**Comment by friend1ws** [comment]
とりあえず、qsub --sync, drmaaができたので、MPIはまた必要になったら入れる。
