### ISSUE TITLE
Regionリスト（ジョブの並列数）について

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#32]
現状の変異Callのジョブ並列につきましては、処理時間にバラつきがあります。

たとえば、以下のようにscaffoldはまとめることができると思います。
samtools view tumor.bam GL000223.1:0-180455 GL000195.1:0-182896 > tumor.sam

処理時間が短いジョブが実行待ち状態になっているともったいないです。

**Comment by friend1ws** [comment]
GLなんちゃらの変異を検出したくなったら考える。
