### ISSUE TITLE
project root directoryを自動生成するか？

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#45]
project root directoryがないとエラーになるけど、これは自動生成した方が良いか？ユーザーに手動で作らせた方が良いか？

**Comment by eigoshimizu** [comment]
実装という面では、簡単です。
ユーザーがすでに作っていたら作らないようにすれば、問題にはなりません。
```
if not os.path.exists( project_dir ):
   os.makedirs( project_dir)

```

**Comment by friend1ws** [comment]
これは個人的には、組み込んでよいと思いますがいかがですかね？？

**Comment by eigoshimizu** [comment]
私もいいと思います。
組み込んで、テストしてゆきます。

**Comment by eigoshimizu** [comment]
Github に commit しました。

**Comment by friend1ws** [comment]
resource/job_file_words.yaml に project_root があると、エラーになってしまうので、こちらをデフォルトでは消していただけますか？

**Comment by friend1ws** [comment]
やはり、helpers/job_check.py でも、resource/job_file_words.yaml に記載がなくても "project_root" をべた書きして、指定してチェックするようになってますよね？これも削除の方向でお願いします。
