### ISSUE TITLE
バージョン管理について

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#48]
Genomon pipelineのバージョンの管理をどうするか？

アイディアその１

・Genomon framework（仮、清水さんがマネージしているrepository)自体にバージョンをふる
・それぞれのmodule (mutation, SV, fusion)にもバージョンをふる
・Genomon framework, それぞれの子モジュールのバージョンの組み合わせを決めて、それ自体をGenomon pipeline全体のバージョンとして、インストールしたり配布する

**Comment by ken0-1n** [comment]
#146と同件
