### ISSUE TITLE
ゲノムリファレンス、アノテーションなど

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#49]
WGSとRNA-seqでアノテーションを出来るだけ揃えるべき。
（chr1と1の違いなどをなくすべき）。

**Comment by ken0-1n** [comment]
リファレンスゲノムがhg19⇒chr1, GRCh37⇒1になる。
WGSとRNAseqでchr1と1の違いをなくすのであれば、リファレンスゲノムを統一するべきだと考えます。

「BAM」と「mutation,SV,fusionなどの候補」にchr1と1の差分があってはいけないと思います。

たとえばBAMが1で、mutationの候補がchr1だと、samtoolsでchr1で調べようとしても、検出できない。
コマンド例：「samtools view hoge.bam chr1:100000-100001」

**Comment by eigoshimizu** [comment]
/home/w3varann/database/GRCh37.fa/GRCh37.fa を 'chr' にしました。

**Comment by ken0-1n** [comment]
hg19⇒chr1, GRCh37⇒1
というのは変更してはいけないもので、

WGSとRNA-seqでchr1,1を揃えるのであれば、
同じリファレンスゲノムを使用してもらえばいいのではないかと思います。なので、変更することはないと考えておりますが、いかがでしょうか？

**Comment by friend1ws** [comment]
これは変更するべきではないですね。
WGSとRNA-seqで両方
/home/w3varann/database/GRCh37.fa/GRCh37.fa
を使えば良いと思います。

**Comment by eigoshimizu** [comment]
了解しました。
genomon.cfg の設定は、下記のようになります。

```
[REFERENCE]
ref_fasta                     = /home/w3varann/database/GRCh37/GRCh37.fa
genome_size                   = /home/w3varann/database/GRCh37/GRCh37.chrom.sizes
chr_str_in_fa                 = False
bowtie2_db                    = /home/w3varann/database/GRCh37.bowtie-2.2.5/GRCh37
ref_gtf                       = /home/w3varann/database/GTF/Homo_sapiens.GRCh37.74.gtf
star_genome                   = /home/w3varann/database/GRCh37.STAR-STAR_2.4.0k
```

**Comment by eigoshimizu** [comment]
/home/w3varann/database/GRCh37.STAR-STAR_2.4.0k は、現在作成中です。
