### ISSUE TITLE
pythonのバージョンの統一について

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#55]
Genomon-Pipelineで必要なpythonのバージョンと
Genomon-SV、MutationFilterなどで使用するpythonが同じバージョンで動くと良い。

**Comment by friend1ws** [comment]
とりあえず
PYTHONPATH=/home/w3varann/.local/lib/python2.7/site-packages
PYTHONHOME=/usr/local/package/python2.7/current
LD_LIBRARY_PATH=/home/w3varann/.local/lib:${PYTHONHOME}/lib:${LD_LIBRARY_PATH}

はいかがですかね？？

**Comment by eigoshimizu** [comment]
現在のLD_LIBRARY_PATH の指定は問題がありますね。
動作を確認したのであれば、いいと思います。
こちらでもテストしてみます。

**Comment by friend1ws** [comment]
特にこだわりはないので、清水さんが大丈夫だと思う環境を、w3varannのgenomon.cfgに記載していただけると嬉しいです。

**Comment by friend1ws** [comment]
Genomon-SV, MutationFilterなどのインストール先はどちらにしますかね？
/home/w3varann/.local/lib　?

**Comment by eigoshimizu** [comment]
python setup.py でインストールできるのであれば、.local が良いと思います。

**Comment by friend1ws** [comment]
virtualenv packageの使用を検討しても良いと思います。
https://virtualenv.pypa.io/en/latest/index.html

ちょっと使ってみましたが、パッケージを使う流れとしては
１．pip install virtualenv　でインストール
２．virtualenv ${ENV} で${ENV}ディレクトリにpythonのexecutable, ライブラリなどが生成される
３．${ENV}/bin/activate　を実行すると、ヴァーチャル環境に入れて（実態は${PYTHONHOME}をunsetして、pathを${ENV}以下に設定するということをしている）
４．この状態で、pip install や python setup.py install をすると、${ENV}/lib/python2.7/site-packages 以下にパッケージがインストールされる
５．virtual environmentから出るには deactivate と打てば（activate時に関数を読み込んで、セットされる）良い。

例えばHGCに設定するとすると
１．w3varann などにvirtual environmentを作成して、そこに必要なpackageをインストール
２．activate → Genomon pipeline 実行 → deactivate の流れのラッパーを作成して、それをユーザーが使うという流れですかね。。。

実際にちょっと使ってみると、PYTHONPATH, LD_LIBRARY_PATHは、unsetされないので、完全にはisolateされた環境にはならないので、ユーザーがこれらの環境変数を設定していると、パッケージを呼ばれる優先度が変わりうるっぽいので注意が必要ですね。あとは、fusionfusionやGenomonSVは簡単にインストールできましたが、numpy見たいな少し複雑なパッケージはインストールに失敗。。必要なパッケージを全部インストールするのは少し大変かもしれません。

まあ、このパッケージを使わないにしても、ここで利用されているテクニック（python関連の環境変数をunsetするなど？）は参考になりうる気がします。

**Comment by ken0-1n** [comment]
以下のパスを追加することで解決した
PYTHONPATH=/home/w3varann/.local/lib/python2.7/site-packages
PYTHONHOME=/usr/local/package/python2.7/current
LD_LIBRARY_PATH=/home/w3varann/.local/lib:${PYTHONHOME}/lib:${LD_LIBRARY_PATH}
