### ISSUE TITLE
run.shを削除して、python genomon.pyで起動できるようにする。

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#56]
run.shを削除して、python genomon.pyで起動できるようにしたほうが良いかと思います。

①LD_LIBRARY_PATH、PYTHONPATHは別の環境設定ファイルに記述する。
②--config_file, --jobsなどのオプションのデフォルト値はgenomon.pyの中に持つ

**Comment by friend1ws** [comment]
これは、むしろ、スクリプトファイルつくって（GenomonSV, mutation filterのような感じ）、argparseのsubparserを利用して

Genomon wgs ${input}.yaml
Genomon rna ${input}.yaml
Genomon star ${input}.yaml

のように出来るのが良いと思います。

**Comment by eigoshimizu** [comment]
genomon.py から、 Genomon にファイル名を変更します。
job_file_chek.py から、 job_file_check にファイル名を変更します。

setenv.sh を加えます。

セットアップ用に、
setup.py
requirements.txt
を加えます。


setenv.sh を実行後、
python Genomon で起動できるようになります。
