### ISSUE TITLE
STAR 実行時間：実績では5時間以下。

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/GenomonPipeline#59]
cmd_options:でljob指定にしているのは敢えてなのでしょうか？
変更してもよいのでは？
 #            star:             '-l ljob,s_vmem=32G,mem_req=32G'
            star:             '-l s_vmem=32G,mem_req=32G -soft -l ljob'

**Comment by eigoshimizu** [comment]
ご指摘の通りです。
最初のほうで、queueを指定してもしなくても ljobに入っていたので、何も考えずに ljob にしてしまいました。
ljob を除いた方が良いと思います。

sample の YAML の方も変更いたしますので、このスレッドはオープンのままにしておいてください。
よろしくお願いいたします。
