### ISSUE TITLE
sample1プロジェクト実行中に 'pipeline.stage_10' でエラー発生

### ISSUE THREAD

**Issue by aokad** [Genomon-Project/GenomonPipeline#62]
エラーになったのが、stage_10なのか、そのあとの終了処理なのかはわかりませんが
コンソールは以下のように出力されていました。

<pre>
    Completed Task = 'helpers.wgs_pipeline.stage_9'
    Task enters queue = 'helpers.wgs_pipeline.stage_10'
    main: Unexpected error
    <class 'ruffus.ruffus_exceptions.RethrownJobError'>: Genomon:488
</pre>

このときのログでは以下だけがエラーらしきものを出力していました。

<pre>
$ tail -n 10  itd_detection_tumor_20150806_1543_624295.sh.e785664.1
rm: cannot remove `./results/small/out/20150806/itd/small/tmp/tmp.bp.left.txt': そのようなファイルやディレクトリはありません
rm: cannot remove `./results/small/out/20150806/itd/small/tmp/juncListitd16_right.txt': そのようなファイルやディレクトリはありません
rm: cannot remove `./results/small/out/20150806/itd/small/tmp/juncListitd16.list': そのようなファイルやディレクトリはありません
rm: cannot remove `./results/small/out/20150806/itd/small/tmp/juncListitd16_left.txt': そのようなファイルやディレクトリはありません
rm: cannot remove `./results/small/out/20150806/itd/small/tmp/juncListitd16.inhouse.1.txt': そのようなファイルやディレクトリはありません
rm: cannot remove `./results/small/out/20150806/itd/small/tmp/juncListitd16.inhouse.2.txt': そのようなファイルやディレクトリはありません
check_error $?
+ check_error 0
+ '[' 0 -ne 0 ']'
</pre>

**Comment by eigoshimizu** [comment]
itd_detection_tumor_20150806_1543_624295.sh.e785664.1 を見てみたいのですが、
場所はどこになりますか？

**Comment by eigoshimizu** [comment]
解析途中で detectITD.sh が失敗しているものと思われます。
使用されているデータが、100 reads の小さいデータなので、ITDは上手く検出されないサンプルです。
’そのようなファイルやディレクトリはありません’ とメッセージが出ているのは、ITDと同定されそうな変異が全く検出されないために中間ファイルが作成されていないものと思われます。
exit code は、0 なので、失敗はしていないものと思われます。

とりあえずこれ以上は追跡できないので、closeします。

**Comment by friend1ws** [comment]
追跡出来ないからってクローズするのはやめてください。
