### ISSUE TITLE
８月７日に話したい議題

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#66]
・tsv形式の入力にしたときに、背後にsample.yamlを生成する感じなのか？だとすると、どういった構造を生成する感じなのかを確認したい。

・上記に関連して、defaultのディレクトリ構造を確認して、テストをその場合に集中するようにしたい。これについてだけ安定的に動けば，短期的にはOKだと思う。

・sample_name, sample_subdirの関係性について理解したい。現状ではsample_subdirの方が実質的なサンプル名をさしているものになっているように見える。うまく現状の構造を生かしつつ、変更を最小限に、自然なものにできないか？例えばsample_name → group_name, sample_subdir → sample_dirのようにする？？

・sample_subdirがあるときとないときについて、プログラムの構造が大幅に変わってしまっている気がするが、今後の可読性のために、これらを統一できないのか？？

・パイプラインの組み込みの際に、@files, @check_if_updateのパラメータを生成するための機能を簡単に開発できるか議論したい。

・Sample classで、最初にjobを一通り全部作成することは出来ないか？今後のデータの大規模化にそなえて、とりあえず、その度にparameterを作成する方が良いのか？

**Comment by friend1ws** [comment]
今日決まったこと（間違っていたら修正お願いします）

sample_name → sample_grouptにする
sample_subdir → sample_name とする？

ディレクトリ構造としては（genomeの場合）、csvを読み込むと
以下の形が出来る（sample_subdirに対応していたものがある前提）
project_dir_tree:
    project_directory:
        data:
            sample_name:
        results:
            sample_name:
                - all_summmary
                - config
                - script
                - log
                - out:
                    - fastq
                    - bam
                    - analysis_date:
                        - mutation
                        - summary
                        - itd

この形のyamlで開発、テストを行う。

**Comment by eigoshimizu** [comment]
CSV の形式

```
#Input 
#sample, fastq1, fastq2
s_B1N, fastq1, fast2
s_B1T, fastq2, fast2
s_B2N, fastq1, fastq2
s_B3N, fastq1, fastq2

#Compare
#Normal, Tumor
s_B1N;s_B2N, s_B1T --> s_B1T
s_B2N, s_B1T --> s_B1T
s_B1N, s_B1T --> s_B1T
    --> Parser stops analysis.

s_B2N, s_B2T
,s_B3T
s_B4N,

s_B5N, s_B5T;s_B6T --> s_B5T
s_B5N, s_B4T --> s_B4T
s_B5N, s_B7T --> s_B7T
```

**Comment by eigoshimizu** [comment]
Genomonの実行方法

Genomon [WGS/STAR/RNA] [analysis output directory] [sample data CSV file]
