### ISSUE TITLE
@check_if_uptodateについて

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#68]
ruffusの機能で
@check_if_uptodate はファイルの依存関係をチェックするはずだが、
一方で
@files　も依存関係をチェックする（一番目が入力、２番目が出力）

マニュアルには@check_if_uptodateは@parallelと一緒に使うのが普通と記載されているが
http://www.ruffus.org.uk/tutorials/new_tutorial/check_if_uptodate.html

現在の書き方では、@check_if_uptodateと@filesで二重に依存関係をチェックしていることになっているように思える。
今後誤解を生む作りになってしまっているように思えるので、対処した方が良いと思う。@filesを@paralleに変更したら良いのか？
あと、現在の挙動としては大丈夫だろうか？例えば@filesと@check_if_uptodateで不一致が生じた場合はどうなるのであろう？

**Comment by eigoshimizu** [comment]
@parallel を使用して、テストしてみました。

結果として、check_file_exists_xxxx 関数が呼ばれなくなりました。
ruffus を実装し始めた時に、@parallelでやっても、 check_file_exists_xxx が呼ばれなくて、@files にすると呼ばれたので、そのまま @files を使用し続けています。

原因を調べなければなりません。

**Comment by friend1ws** [comment]
了解です。そうですね、しばらく@filesを使う感じで行きましょうか。
でも、ちょっと気持ち悪いのもあるので、早めに原因を調べましょう。
簡単なexample codeを作ってみて、

```
from ruffus import *
import os
def check_file_exists(input_file, output_file):
    if os.path.exists(output_file):
        return False, "File already exists"
    return True, "%s is missing" % output_file

@parallel([[None, "a.1"]])
@check_if_uptodate(check_file_exists)
def create_if_necessary(input_file, output_file):
    open(output_file, "w")

pipeline_run([create_if_necessary])
```

**Comment by friend1ws** [comment]
ちなみに、@parallelと@check_if_uptodateの順序を逆にしたら、うまくいったっぽいです。

**Comment by eigoshimizu** [comment]
テストしました。
動作確認です。
ありがとうございます。

**Comment by eigoshimizu** [comment]
現在テスト中ですが、結果が @parallel と @files の結果が違ってきてしまいます。
下記のファイルでテストしていますが、 @parallel だと、 s_B3N がパラメータとして返されませんでした。
原因はわかりません。

```
#Input	
#sample	
s_B1N	/home/eigos/Data/GenomonProj/input/DvsC/s_B1N/R1.fastq
s_B1T	/home/eigos/Data/GenomonProj/input/DvsC/s_B1T/R1.fastq
s_B2Na	/home/eigos/Data/GenomonProj/input/DvsC/s_B2Na/R1.fastq
s_B2Nb	/home/eigos/Data/GenomonProj/input/DvsC/s_B2Nb/R1.fastq
s_B2T	/home/eigos/Data/GenomonProj/input/DvsC/s_B2T/R1.fastq
s_B3N	/home/eigos/Data/GenomonProj/input/DvsC/s_B3N/R1.fastq
s_B3Ta	/home/eigos/Data/GenomonProj/input/DvsC/s_B3Ta/R1.fastq
s_B3Tb	/home/eigos/Data/GenomonProj/input/DvsC/s_B3Tb/R1.fastq
s_B4N	/home/eigos/Data/GenomonProj/input/DvsC/s_B4N/R1_1.fastq;/home/eigos/Data/GenomonProj/input/DvsC/s_B4N/R2_1.fastq
s_B4Ta	/home/eigos/Data/GenomonProj/input/DvsC/s_B4Ta/R1.fastq
	
	
#Compare	
#normal	tumor
s_B1N	s_B1T
s_B2Na;s_B2Nb	s_B2T
s_B3N	s_B3Ta;s_B3Tb
s_B4N	s_B4Ta
```

**Comment by friend1ws** [comment]
この件ってどうなりました？
ちなみに@parallelはバグがあることは作者もみとめていて、次のバージョンで対処されるようです。

https://github.com/bunbun/ruffus/issues/53
