### ISSUE TITLE
star_pipelineは複数のfastqを受け取ることが出来ますか？

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/GenomonPipeline#73]
ソースをチラ見した限り、現状は対応していないと思ったのですが、その認識でOKですか？
確認したいだけで、対応していないならばそのままでもOKだと思います（RNA-seqはマージしないと行けないケースが少ないので）。

**Comment by eigoshimizu** [comment]
ご指摘の通り、現状は対応していません。
STAR pipeline では、CSVの入力フォーマットはサポートしていません。
この issue は、 Open のままにしておきます。
