### ISSUE TITLE
mutation callするときにBAMをコピーする動作について

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#75]
mutation callをするときに対象のbamをmutationディレクトリにコピーしているのでしょうか？
コピー元
$ ll ~/tmp/results/german/out/bam/s_German_V_021/german_markdup.bam
-rw-rw---- 1 hogehoge 1735879855 Aug 15 11:44 
コピー先
$ ll ~/tmp/results/german/out/150101/mutation/s_German_V_021/german.bam
-rw-rw---- 1 hogehoge 1735879855 Aug 15 11:45 

コピーに時間かかる＆一時的であってもDisk容量がもったいないのでやめた方が良いかと思います。

最終的な仕様としては、複数のBAMの入力があった場合に、BAMをマージしてmutationディレクトリに置くのではなく、BAMを複数fisherに入力できるようにするのが目標です。

**Comment by eigoshimizu** [comment]
ご指摘の通り、
BAM ファイルが複数の時は、マージしますが、BAM ファイルが１つの時は、コピーしています。

ご提案の通り、fisher.py のインターフェースを変えて、複数の mpileup を受け付けられるようにするのが良いと思います。

**Comment by eigoshimizu** [comment]
とりあえずコピーの代わりに、リンクに変更します。

**Comment by eigoshimizu** [comment]
千葉さんに assign します。
”最終的な仕様としては、複数のBAMの入力があった場合に、BAMをマージしてmutationディレクトリに置くのではなく、BAMを複数fisherに入力できるようにするのが目標です。”
