### ISSUE TITLE
FASTQのsplitが実行されない

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#89]
FASTQのsplitが実行されないのでチェックお願いします。
スクリプトは、8/28 12:30時点のdevelopを使用しました。
fisherの結果が出力されることを確認していただければと思います。

コマンドはこちら
bash run.sh  DNA /home/kchiba/tmp/Genomon_german21_test /home/kchiba/work_genomonprj/Genomon/samples/sample_german21.tsv

german21.tsvは使用してもらって大丈夫です。

**Comment by ken0-1n** [comment]
Stage「Fastq split」にはCasavaのquality checksでFilterするべきとされた行をフィルタする機能がついている。
「grep -A 3 '^@.* [^:]*:N:[^:]*:'」、このスクリプトでN以外の行をfilterする。

Bam ⇒ Fastq にすると NもYもないFASTQが作成される。そしてfilter機能をONにしていると、N以外の行はフィルタされてしまうので、空のFASTQファイルが作成される。

フィルタの条件を修正しなければ、ならない。
例えば、NもYもなければ、フィルタしないとかが必要。

**Comment by eigoshimizu** [comment]
Y の時だけフィルターでのぞけそうです。
grep -v -A3 '^@.* [^:]*:Y:[^:]*:'
どうでしょうか？
