### ISSUE TITLE
fisher_mutation_call でBAMのファイルサイズを確認しているif文について(確認)

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#90]
bamfilter.pyのあとにif文があって、サイズがほぼ0byteのBAMはmpileupとfisher.pyをスキップしているようにみえます。fisher.pyの候補数が0件の場合、header行の出力は不要でしょうか？

以下、bamfilter.pyのあとのif文
if [ -e "$CONTROL_FILTERED_BAM"  ]
then
    SIZE_OF_CONTROL_BAM=`du -b $CONTROL_FILTERED_BAM | sed 's/\([0-9\.]\+\).\+/\\1/'`
else
    SIZE_OF_CONTROL_BAM=0
fi
if [ -e "$DISEASE_FILTERED_BAM"  ]
then
    SIZE_OF_DISEASE_BAM=`du -b $DISEASE_FILTERED_BAM | sed 's/\([0-9\.]\+\).\+/\\1/'`
else
    SIZE_OF_DISEASE_BAM=0
fi

if [ $SIZE_OF_CONTROL_BAM -gt 300 -a $SIZE_OF_DISEASE_BAM -gt 300 -a ! -e $INTERVAL_OUT  ]
then

**Comment by eigoshimizu** [comment]
header行の出力は不要です。
テストの段階で、headerをみて確認していました。
最終的にアノテーションした結果がわかるようにheaderが出力されれば良いと思います。
候補件数が０の時は、headerを出力しなくても良いと思います。
そうすれば、ファイルサイズの判断が確実で簡単になると思います。
よろしくお願いいたします。

**Comment by ken0-1n** [comment]
候補件数は1以上であるが、first intervalの候補0件が場合も、問題ないという認識で大丈夫でしょうか？

**Comment by eigoshimizu** [comment]
merge_fisher_resultの中では、一番最初のinterval の出力ファイルから、ヘッダーを取得しているようです。
このコードは、出力に必ずヘッダーが出力されるものと仮定しているので、ヘッダーがないと問題になりますね。

fisherの結果に、ヘッダーがなくても良いのであれば、merge_fisher_resultのヘッダーを取得する部分を削除してしまえば良いと思います。
この部分：
```
FIRST_INTERVAL=`echo $INTERVAL_LIST | head -1 | sed 's/^\([^ ]\+\) .\+$/\\1/g'`
INTERVAL_OUT=`echo {output_txt} | sed "s/\.txt/_$FIRST_INTERVAL.txt/"`

head -1 $INTERVAL_OUT > {output_txt}

```

**Comment by ken0-1n** [comment]
bamfilter.pyのあとのif文を削除して、BAMが空（headerだけ)でも、fisher.pyを起動して、headerだけ出力するように変更します。
