### ISSUE TITLE
bam_stats_mergeの再実行について

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#91]
1回目の実行で、bam_stats_mergeでエラーとなって、
再実行したらbwa_memから再実行された、

mark_dup.bamが存在するので、bam_stats_mergeから再実行してほしいです。

★1回目の実行　（bam_stats_merge_20150831_1123_122781がエラーとなる）
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    （省略）
    qsub
    command     = -t 1-1:1,     /home/kchiba/tmp/Genomon_german21_test/./results/analysis/script/bam_stats_merge_20150831_1123_122781.sh
    cmd_options = -l s_vmem=6G,mem_req=6G

```
STDOUT: Your job-array 1523182.1-1:1 ("bam_stats_merge_20150831_1123_122781.sh") has been submitted
Job 1523182 exited with exit code 1.

STDERR:

bam_stats_merge: runtask failed
bam_stats: Unexpected error: <type 'exceptions.Exception'>
<type 'exceptions.Exception'>: wgs_pipeline.py:1920
#sv_detection_parse
sv_detection_parse: Unexpected error: <type 'exceptions.KeyError'>
<type 'exceptions.KeyError'>: wgs_pipeline.py:2485
#sv_detection_parse
sv_detection_parse: Unexpected error: <type 'exceptions.KeyError'>
<type 'exceptions.KeyError'>: wgs_pipeline.py:2485
Completed Task = 'helpers.wgs_pipeline.stage_10'
Task enters queue = 'helpers.wgs_pipeline.sv_detection_filt'
021T
021N
```

★再実行（bwa_mem_20150831_1418_150007.sh）が実行される
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

```
-bash-4.1$  bash run.sh --verbose 2 DNA /home/kchiba/tmp/Genomon_german21_test     　　/home/kchiba/work_genomonprj/Genomon/samples/sample_german21.tsv

Generated by ./Genomon
Analysis          = DNA
Output directory  = /home/kchiba/tmp/Genomon_german21_test
Sample list file  = /home/kchiba/work_genomonprj/Genomon/samples/sample_german21.tsv
RunTask: run_mode=qsub

________________________________________
Tasks which are up-to-date:


Task = 'helpers.wgs_pipeline.stage_1'
Task = 'helpers.wgs_pipeline.stage_2'
Task = 'helpers.wgs_pipeline.stage_3'
________________________________________



________________________________________
Tasks which will be run:


Task enters queue = 'helpers.wgs_pipeline.stage_4'
#bwa_mem
#bwa_mem
qsub
qsub
command     = -t 1-1:1,   　　/home/kchiba/tmp/Genomon_german21_test/./results/analysis/script/bwa_mem_20150831_1418_150007.sh
command     = -t 1-1:1, 　　/home/kchiba/tmp/Genomon_german21_test/./results/analysis/script/bwa_mem_20150831_1418_150160.sh
cmd_options = -l s_vmem=8G,mem_req=8G
```

★merged.bamは存在する。
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
-rw-rw---- 1 kchiba hgc0361 1444046879 Aug 31 11:14 021N_markdup.bam
-rw-rw---- 1 kchiba hgc0361    4594336 Aug 31 11:14 021N_markdup.bam.bai
-rw-rw---- 1 kchiba hgc0361       2537 Aug 31 11:14 021N_markdup.bam.met
-rw-rw---- 1 kchiba hgc0361          0 Aug 31 11:14 021N_merged.bam
-rw-rw---- 1 kchiba hgc0361          0 Aug 31 11:14 1_1_000001_unsorted.bam
-rw-rw---- 1 kchiba hgc0361          0 Aug 31 14:18 1_1_000002_unsorted.bam

/home/kchiba/tmp/Genomon_german21_test/./results/analysis/out/bam/021T:
total 3423216
-rw-rw---- 1 kchiba hgc0361 1736168507 Aug 31 11:15 021T_markdup.bam
-rw-rw---- 1 kchiba hgc0361    4414696 Aug 31 11:15 021T_markdup.bam.bai
-rw-rw---- 1 kchiba hgc0361       2537 Aug 31 11:15 021T_markdup.bam.met
-rw-rw---- 1 kchiba hgc0361          0 Aug 31 11:15 021T_merged.bam
-rw-rw---- 1 kchiba hgc0361          0 Aug 31 14:18 1_1_000002_unsorted.bam
-rw-rw---- 1 kchiba hgc0361          0 Aug 31 11:15 1_1_000003_unsorted.bam

**Comment by eigoshimizu** [comment]
bwa memは、1_1_XXXXXX_sorted.bamを見ていますが、_sorted.bamは削除されて、_unsorted.bamがサイズ０のファイルになっています。

wgs_pipeline.py: delete_intermediate_files
if 'bwa_mem' in Geno.job.get_job( 'tasks' )[ 'DNA' ]:

のところの glob を sortすれば、問題は解決します。
よろしくお願いいたします。
Fixしますのて、そちらのサンプルでテストをお願いいたします。

**Comment by ken0-1n** [comment]
genomon pipeline 2.0以前の問題なのでcloseする。現バージョン2.5では問題となっていない。
