### ISSUE TITLE
fisher_mutation_call_merge_bamでエラー

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#92]
link先にファイル存在するとエラーになるのではないでしょうか？

+ '[' False = True ']'
+ ln ./data/analysis/021T/1_1.fastq ./results/analysis/out/20150831/mutation/021T/021T.bam
ln: creating hard link `./results/analysis/out/20150831/mutation/021T/021T.bam': File exists
+ check_error 1
+ '[' 1 -ne 0 ']'
+ echo 'FATAL ERROR: pipeline script'
+ echo 'ERROR CODE: 1'
+ exit 1

**Comment by eigoshimizu** [comment]
エラーになります。バグです。
リンクを貼る前に、ファイルがあるかチェックして、ある場合は削除するコードが必要です。
変更していただけますか？
よろしくお願いいたします。

**Comment by ken0-1n** [comment]
ln -f を入れたら動きました。
ln -f ./data/analysis/021N/1_1.fastq ./results/analysis/out/20150831/mutation/021N/021N.bam

リンクされているものが異なります。

**Comment by eigoshimizu** [comment]
このエラーは今まで見たことがありません。
generate_params_for_fisher_mutation_callで作成されたパラメーターし使っていいないので、何か動作がおかしいです。
トレースしないとわかりません。

詳しいテストケースをお教えください。

**Comment by ken0-1n** [comment]
generate_params_for_fisher_mutation_callでパラメータは作成しております。developで最新版を落としてきてから変更は入れておりません。

こちらのサンプルtsvを使用していただければと思います。
/home/kchiba/work_genomonprj/Genomon/samples/sample_german21.tsv
アライメントも30分程度で完了します。

**Comment by ken0-1n** [comment]
genomon_rc.pyのdefault taskをfisher_mutation_callだけにしたのですが、これが原因でした
default_task = """
DNA:
    - fisher_mutation_call

優先度は下げます。
将来的に対応するかは要相談です。

**Comment by eigoshimizu** [comment]
DNA:
 - fisher_mutation_cal

だけを指定した場合は、入力ファイルにBAMファイルを指定すると動作すると思います。
入力ファイルがFASTQの場合は、ユーザーさんは、アラインメントを必ず指定しなければならないという仕様でどうでしょうか?
