### ISSUE TITLE
STAR:並列実行　run at --runThreadN 6 で処理時間1/3に。

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/GenomonPipeline#98]
１．STAR option --runThreadN 6 を追加
２．'-pe def_slot 6 -l s_vmem=5.3G,mem_req=5.3G'でjob投入（メモリ指定は32GB の1/6にして）
＜結果＞
処理時間が3分の1に短縮される
sortedBAMに要するメモリは　multi threadにしても若干減るだけなので
38GBまで必要だったサンプルのメモリ不足エラーの解決にはならない。

**Comment by friend1ws** [comment]
ありがとうございます。これは思ったよりもすごく良いですね。これでCPUの無駄遣いも効率的に解決ですね。
